version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
     reviewers:
      - "pycodeBE"
    labels:
      - "pip dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "pycodeBE"
    labels:
      - "docker dependencies"
