version: '3.2'

services:
  database:
    container_name: database
    build:
      context: .
      dockerfile:
        docker/database/Dockerfile
    environment:
      - ORACLE_RANDOM_PASSWORD=yes
    volumes:
      - oracle_db:/var/lib/oracle_db
      - oracle_data:/var/lib/oracle_db/data
    networks:
      - dbnet
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus / as sysdba"]
      interval: 20s
      timeout: 20s
      retries: 60
  flyway:
      image: flyway/flyway:latest
      container_name: flyway
      volumes:
        - flyway_sql:/flyway/sql
        - flyway_conf:/flyway/conf
      networks:
        - dbnet
